import java.io.IOException;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;

public class Servidor {
	
	public static void main(String[] args) throws IOException{
		ServerSocket serverSocket = null;
		
		StringBuilder sql = new StringBuilder();


sql.append("<!DOCTYPE html>");
sql.append("<html itemscope itemtype='http://schema.org/QAPage'>");
sql.append("<head>");
sql.append("<title>Java Server: Socket sending HTML code to browser - Stack Overflow</title>");
sql.append("    <link rel='shortcut icon' href='https://cdn.sstatic.net/Sites/stackoverflow/img/favicon.ico?v=4f32ecc8f43d'>");
sql.append("    <link rel='apple-touch-icon image_src' href='https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a'>");
sql.append("    <link rel='search' type='application/opensearchdescription+xml' title='Stack Overflow' href='/opensearch.xml'>");
sql.append("    <meta name='twitter:card' content='summary'>");
sql.append("    <meta name='twitter:domain' content='stackoverflow.com'/>");
sql.append("    <meta property='og:type' content='website' />");
sql.append("    <meta property='og:image' itemprop='image primaryImageOfPage' content='https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon@2.png?v=73d79a89bded' />");
sql.append("    <meta name='twitter:title' property='og:title' itemprop='title name' content='Java Server: Socket sending HTML code to browser' />");
sql.append("    <meta name='twitter:description' property='og:description' itemprop='description' content='I am trying to write a simple Java program using ServerSockets that will send some HTML code to the browser. Here is my code:");
sql.append("       ServerSocket serverSocket = null;");
sql.append("       try {");
sql.append("             ' />");
sql.append("    <meta property='og:url' content='http://stackoverflow.com/questions/15889331/java-server-socket-sending-html-code-to-browser'/>");
sql.append("    <link rel='canonical' href='http://stackoverflow.com/questions/15889331/java-server-socket-sending-html-code-to-browser' />");
sql.append("    <script src='https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js'></script>");
sql.append("    <script src='https://cdn.sstatic.net/Js/stub.en.js?v=f574431de552'></script>");
sql.append("    <link rel='stylesheet' type='text/css' href='https://cdn.sstatic.net/Sites/stackoverflow/all.css?v=be68eba2e8c5'>");
sql.append("            <link rel='alternate' type='application/atom+xml' title='Feed for question &#39;Java Server: Socket sending HTML code to browser&#39;' href='/feeds/question/15889331'>");
sql.append("            <meta name='twitter:app:country' content='US' />");
sql.append("            <meta name='twitter:app:name:iphone' content='Stack Exchange iOS' />");
sql.append("            <meta name='twitter:app:id:iphone' content='871299723' />");
sql.append("            <meta name='twitter:app:url:iphone' content='se-zaphod://stackoverflow.com/questions/15889331/java-server-socket-sending-html-code-to-browser' />");
sql.append("            <meta name='twitter:app:name:ipad' content='Stack Exchange iOS' />");
sql.append("            <meta name='twitter:app:id:ipad' content='871299723' />");
sql.append("            <meta name='twitter:app:url:ipad' content='se-zaphod://stackoverflow.com/questions/15889331/java-server-socket-sending-html-code-to-browser' />");
sql.append("            <meta name='twitter:app:name:googleplay' content='Stack Exchange Android'>");
sql.append("            <meta name='twitter:app:url:googleplay' content='http://stackoverflow.com/questions/15889331/java-server-socket-sending-html-code-to-browser'>");
sql.append("            <meta name='twitter:app:id:googleplay' content='com.stackexchange.marvin'>");
sql.append("        <script>       ");
sql.append("            StackExchange.ready(function () {                      ");
sql.append("                    StackExchange.using('snippets', function () {");
sql.append("                        StackExchange.snippets.initSnippetRenderer();");
sql.append("                    });");
sql.append("                StackExchange.using('postValidation', function () {");
sql.append("                    StackExchange.postValidation.initOnBlurAndSubmit($('#post-form'), 2, 'answer');");
sql.append("                });  ");
sql.append("                StackExchange.question.init({showAnswerHelp:true,totalCommentCount:3,shownCommentCount:3,highlightColor:'#F4A83D',backgroundColor:'#FFF',questionId:15889331});");
sql.append("                styleCode();");
sql.append("                    StackExchange.realtime.subscribeToQuestion('1', '15889331');");
sql.append("                                                                    StackExchange.using('gps', function () { StackExchange.gps.trackOutboundClicks('#content', '.post-text', true); });");
sql.append("            });");
sql.append("        </script>");
sql.append("    <script>");
sql.append("        StackExchange.init({'locale':'en','stackAuthUrl':'https://stackauth.com','networkMetaHostname':'meta.stackexchange.com','serverTime':1489444423,'routeName':'Questions/Show','site':{'name':'Stack Overflow','description':'Q&A for professional and enthusiast programmers','isNoticesTabEnabled':true,'recaptchaPublicKey':'6LdchgIAAAAAAJwGpIzRQSOFaO0pU6s44Xt8aTwc','recaptchaAudioLang':'en','enableNewTagCreationWarning':true,'insertSpaceAfterNameTabCompletion':false,'id':1,'enableInsertDocLinkDialog':true,'enableSocialMediaInSharePopup':true,'protocol':'http'},'user':{'fkey':'4b002d7c7ab0bc9ed3cd9eeec9dd2f5c','rep':0,'isAnonymous':true,'isAnonymousNetworkWide':true,'canSeeNewHeaderDesign':true,'ab':{'question_show_tweaks':{'v':'altern_unansw_cta','g':2},'simplified_signup_form':{'v':'messaging_b','g':2}}},'events':{'postType':{'question':1},'postEditionSection':{'title':1,'body':2,'tags':3}},'story':{'minCompleteBodyLength':75}}, {'site':{'allowImageUploads':true,'enableUserHovercards':true,'styleCode':true,'enableNewLinkInsertDialog':true,'enableImgurHttps':true,'forceHttpsImages':true},'comments':{},'userProfile':{'openGraphAPIKey':'58740831ad23540e00c58987'},'tags':{},'accounts':{'currentPasswordRequiredForChangingStackIdPassword':true},'flags':{'allowRetractingFlags':true},'analytics':{'clientTimingsAbsoluteTimeout':30000,'clientTimingsDebounceTimeout':1000},'snippets':{'snippetsEnabled':true,'renderDomain':'stacksnippets.net'},'markdown':{'asteriskIntraWordEmphasis':true}});");
sql.append("        StackExchange.using.setCacheBreakers({'js/prettify-full.en.js':'c887f62199b3','js/moderator.en.js':'2e689ad01392','js/full-anon.en.js':'de857b728b4b','js/full.en.js':'da8ab4498029','js/wmd.en.js':'4275a5e43e65','js/third-party/jquery.autocomplete.min.js':'d3b8fa7fdf74','js/third-party/jquery.autocomplete.min.en.js':','js/mobile.en.js':'c37948fe0a99','js/help.en.js':'dbd4f489eff2','js/tageditor.en.js':'7968c1573954','js/tageditornew.en.js':'4afae342e456','js/inline-tag-editing.en.js':'2ddfa79492e7','js/revisions.en.js':'8f22ba768cac','js/review.en.js':'115707a743f2','js/tagsuggestions.en.js':'b278f9a0b23b','js/post-validation.en.js':'5fa8a0489267','js/explore-qlist.en.js':'e71f14781288','js/events.en.js':'69c5ed9eaef8','js/keyboard-shortcuts.en.js':'5a00895523f7','js/external-editor.en.js':'cb487078c372','js/adops.en.js':'9a6a7812a212','js/external-editor.en.js':'cb487078c372','js/snippet-javascript.en.js':'e76aab1cc9bc','js/snippet-javascript-codemirror.en.js':'11bcb603270e'});");
sql.append("        StackExchange.using('gps', function() {");
sql.append("             StackExchange.gps.init(true);");
sql.append("        });");
sql.append("    </script>");
sql.append("        <script>");
sql.append("            StackExchange.ready(function () {");
sql.append("                $('#nav-tour').click(function () {");
sql.append("                    StackExchange.using('gps', function() {");
sql.append("                        StackExchange.gps.track('aboutpage.click', { aboutclick_location: 'headermain' }, true);");
sql.append("                    });");
sql.append("                });");
sql.append("            });");
sql.append("        </script>");
sql.append("    <noscript id='noscript-css'><style type='text/css'>body,.so-header{margin-top:1.9em}</style></noscript>");
sql.append("</head>");
sql.append("<body class='question-page new-topbar'>");
sql.append("            <script>(function () { var old = $.fn.contents; $.fn.contents = function () { try { return old.apply(this, arguments); } catch (e) { return $([]); } } })()</script>");
sql.append("        <iframe id='adzerk-user-match' width='0' height='0' frameborder='0' scrolling='no' onload='window.AUMIframeDone=true'");
sql.append("                src='https://ssum-sec.casalemedia.com/usermatch?s=183712&amp;cb=https%3A%2F%2Fengine.adzerk.net%2Fudb%2F22%2Fsync%2Fi.gif%3FpartnerId%3D1%26userId%3D'");
sql.append("                style='display: none;' marginheight='0' marginwidth='0'></iframe>");
sql.append("    <div id='notify-container'></div>");
sql.append("    <div id='custom-header'></div>");
sql.append("<header class='so-header js-so-header _fixed'>");
sql.append("    <div class='-container'>");
sql.append("        <div class='-main'>            ");
sql.append("            <a href='http://stackoverflow.com' class='-logo '>");
sql.append("                <span class='-img'>Stack Overflow</span>");
sql.append("            </a>");
sql.append("            <nav class='navigation'>");
sql.append("                <ol class='-list'>");
sql.append("                        <li class='-item _current'>");
sql.append("        <a id='nav-questions' href='/questions' class='-link js-gps-track' ");
sql.append("            data-gps-track='top_nav.click({is_current:true, location:2, destination:1})'>Questions</a>");
sql.append("    </li>");
sql.append("    <li class='-item'>");
sql.append("        <a id='nav-jobs' href='/jobs?med=site-ui&amp;ref=jobs-tab' class='-link js-gps-track' ");
sql.append("            data-gps-track='top_nav.click({is_current:false, location:2, destination:6})'>Jobs</a>");
sql.append("    </li>");
sql.append("                        <li class='-item'>");
sql.append("        <a id='nav-docs' href='/documentation' class='-link js-gps-track' ");
sql.append("            data-gps-track='top_nav.click({is_current:false, location:2, destination:7})'>Documentation <small class='beta-badge'>beta</small></a>");
sql.append("    </li>");
sql.append("                        <li class='-item'>");
sql.append("        <a id='nav-tags' href='/tags' class='-link js-gps-track' ");
sql.append("            data-gps-track='top_nav.click({is_current:false, location:2, destination:2})'>Tags</a>");
sql.append("    </li>");sql.append("                        <li class='-item'>");
sql.append("        <a id='nav-users' href='/users' class='-link js-gps-track' ");
sql.append("            data-gps-track='top_nav.click({is_current:false, location:2, destination:3})'>Users</a>");
sql.append("    </li>");
sql.append("                </ol>");
sql.append("            </nav>");sql.append("            <form id='search' action='/search' method='get' class='searchbar' autocomplete='off'>");
sql.append("                <svg viewBox='0 0 18 18' width='18' height='18' role='icon'><path fill-rule='evenodd' d='M12.864 11.32h-.813l-.288-.277A6.66 6.66 0 0 0 13.38 6.69a6.69 6.69 0 1 0-6.69 6.69 6.66 6.66 0 0 0 4.354-1.617l.278.288v.813L16.467 18 18 16.467l-5.136-5.146zm-6.174 0a4.625 4.625 0 0 1-4.632-4.63A4.625 4.625 0 0 1 6.69 2.058a4.625 4.625 0 0 1 4.63 4.632 4.625 4.625 0 0 1-4.63 4.63z'/></svg>");
sql.append("                <input name='q' type='text' placeholder='Search...' value=' tabindex='1' autocomplete='off' maxlength='240' class='f-input js-search-field' />");
sql.append("                <button type='submit' class='btn js-search-submit'>");
sql.append("                    <svg viewBox='0 0 18 18' width='18' height='18' role='icon'><path fill-rule='evenodd' d='M12.864 11.32h-.813l-.288-.277A6.66 6.66 0 0 0 13.38 6.69a6.69 6.69 0 1 0-6.69 6.69 6.66 6.66 0 0 0 4.354-1.617l.278.288v.813L16.467 18 18 16.467l-5.136-5.146zm-6.174 0a4.625 4.625 0 0 1-4.632-4.63A4.625 4.625 0 0 1 6.69 2.058a4.625 4.625 0 0 1 4.63 4.632 4.625 4.625 0 0 1-4.63 4.63z'/></svg>");
sql.append("                </button>");
sql.append("            </form>");sql.append("        </div>");
sql.append("<div class='-actions'>");
sql.append("    <nav class='secondary-nav'>");
sql.append("        <div class='-dialog-container js-topbar-dialog-corral'>");
sql.append("    <div class='topbar-dialog siteSwitcher-dialog dno'>");
sql.append("        <div class='header'>");
sql.append("            <h3><a href='http://stackoverflow.com'>current community</a>");
sql.append("            </h3>");
sql.append("        </div>");
sql.append("        <div class='modal-content current-site-container'>");
sql.append("            <ul class='current-site'>");
sql.append("                    <li>");
sql.append("                            <div class='related-links'>");
sql.append("                    <a href='http://stackoverflow.com/help' class='js-gps-track'     data-gps-track='site_switcher.click({ item_type:14 })'");
sql.append(">help</a>");
sql.append("                    <a href='http://chat.stackoverflow.com' class='js-gps-track'     data-gps-track='site_switcher.click({ item_type:6 })'");
sql.append(">chat</a>");
sql.append("            </div>");
sql.append("    <a href='http://stackoverflow.com'");
sql.append("       class='current-site-link site-link js-gps-track'");
sql.append("       data-id='1'");
sql.append("       data-gps-track='site_switcher.click({ item_type:3 })'>");
sql.append("        <div class='site-icon favicon favicon-stackoverflow' title='Stack Overflow'></div>");
sql.append("        Stack Overflow");
sql.append("    </a>");
sql.append("                    </li>");
sql.append("                    <li class='related-site'>");
sql.append("                            <div class='L-shaped-icon-container'>");
sql.append("        <span class='L-shaped-icon'></span>");
sql.append("    </div>                ");
sql.append("    <a href='https://meta.stackoverflow.com'");
sql.append("       class='site-link js-gps-track'");
sql.append("       data-id='552'");
sql.append("       data-gps-track='site.switch({ target_site:552, item_type:3 }),site_switcher.click({ item_type:4 })'>");
sql.append("        <div class='site-icon favicon favicon-stackoverflowmeta' title='Meta Stack Overflow'></div>");
sql.append("        Meta Stack Overflow");
sql.append("    </a>");
sql.append("                    </li>");
sql.append("            </ul>");
sql.append("        </div>");sql.append("        <div class='header' id='your-communities-header'>");
sql.append("            <h3>");
sql.append("your communities            </h3>");
sql.append("        </div>");
sql.append("        <div class='modal-content' id='your-communities-section'>");
sql.append("                <div class='call-to-login'>");
sql.append("<a href='https://stackoverflow.com/users/signup?ssrc=site_switcher&amp;returnurl=%2fusers%2fstory%2fcurrent&amp;amp;utm_source=stackoverflow.com&amp;amp;utm_medium=dev-story&amp;amp;utm_campaign=signup-redirect' class='login-link js-gps-track'     data-gps-track='site_switcher.click({ item_type:10 })'");
sql.append(">Sign up</a> or <a href='https://stackoverflow.com/users/login?ssrc=site_switcher&amp;returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2f15889331%2fjava-server-socket-sending-html-code-to-browser' class='login-link js-gps-track'     data-gps-track='site_switcher.click({ item_type:11 })'");
sql.append(">log in</a> to customize your list.");
sql.append("                </div>");
sql.append("        </div>");
sql.append("        <div class='header'>");
sql.append("            <h3><a href='https://stackexchange.com/sites'>more stack exchange communities</a>");
sql.append("            </h3>");
sql.append("            <a href='https://stackoverflow.blog' class='fr'>company blog</a>");
sql.append("        </div>");
sql.append("        <div class='modal-content'>");
sql.append("                <div class='child-content'></div>");
sql.append("        </div>        ");
sql.append("    </div>");
sql.append("                <div class='topbar-dialog help-dialog js-help-dialog dno'>");
sql.append("        <div class='modal-content'>");
sql.append("            <ul>");
sql.append("                                    <li>");
sql.append("                        <a href='/tour' class='js-gps-track' data-gps-track='help_popup.click({ item_type:1 })'>");
sql.append("                            Tour");
sql.append("                            <span class='item-summary'>");
sql.append("                                Start here for a quick overview of the site");
sql.append("                            </span>");
sql.append("                        </a>");
sql.append("                    </li>");
sql.append("                <li>");
sql.append("                    <a href='/help' class='js-gps-track' data-gps-track='help_popup.click({ item_type:4 })'>");
sql.append("                        Help Center");
sql.append("                        <span class='item-summary'>");
sql.append("                            Detailed answers to any questions you might have");
sql.append("                        </span>");
sql.append("                    </a>");
sql.append("                </li>");
sql.append("                        <li>");
sql.append("                            <a href='https://meta.stackoverflow.com' class='js-gps-track' data-gps-track='help_popup.click({ item_type:2 })'>");
sql.append("                                Meta");
sql.append("                                <span class='item-summary'>");
sql.append("                                    Discuss the workings and policies of this site");
sql.append("                                </span>");
sql.append("                            </a>");
sql.append("                        </li>");
sql.append("                        <li>");
sql.append("                            <a href='http://stackoverflow.com/company/about' class='js-gps-track' data-gps-track='help_popup.click({ item_type:6 })'>");
sql.append("                                About Us");
sql.append("                                <span class='item-summary'>");
sql.append("                                    Learn more about Stack Overflow the company");
sql.append("                                </span>");
sql.append("                            </a>");
sql.append("                        </li>");
sql.append("                        <li>");
sql.append("                            <a href='https://www.stackoverflowbusiness.com/?ref=topbar_help' class='js-gps-track' data-gps-track='help_popup.click({ item_type:7 })'>");
sql.append("                                Business");
sql.append("                                <span class='item-summary'>");
sql.append("                                    Learn more about hiring developers or posting ads with us");
sql.append("                                </span>");
sql.append("                            </a>");
sql.append("                        </li>");
sql.append("            </ul>");
sql.append("        </div>");
sql.append("    </div>");
sql.append("        </div>");
sql.append("        <ol class='-list'> ");
sql.append("    <li class='-item'><a href='#' class='-link js-help-button' title='Help Center and other resources'>");
sql.append("        <svg viewBox='0 0 18 18' width='18' height='18' role='icon'><path fill-rule='evenodd' d='M9 0a9 9 0 1 0 .001 18.001A9 9 0 0 0 9 0zm.812 13.126c-.02.716-.55 1.157-1.238 1.137-.659-.02-1.177-.49-1.157-1.209.02-.715.566-1.17 1.225-1.15.691.021 1.194.507 1.17 1.222zm1.956-5.114c-.168.237-.546.542-1.02.912l-.527.361c-.257.197-.417.43-.502.695-.044.141-.076.507-.084.752-.004.048-.032.156-.181.156H7.883c-.165 0-.185-.096-.18-.144.023-.667.12-1.218.397-1.66.374-.594 1.426-1.221 1.426-1.221.161-.12.286-.25.382-.39.177-.24.321-.51.321-.8 0-.333-.08-.65-.293-.915-.249-.31-.518-.458-1.036-.458-.51 0-.808.257-1.021.594-.213.338-.177.735-.177 1.097H5.746c0-1.366.357-2.238 1.112-2.752.51-.35 1.162-.502 1.921-.502.996 0 1.788.184 2.487.715.647.49.988 1.181.988 2.113 0 .575-.2 1.057-.486 1.447z' /></svg>");
sql.append("    </a></li>");
sql.append("                <li class='-item'>");
sql.append("        <a href='https://stackexchange.com' class='-link js-site-switcher-button js-gps-track' data-gps-track='site_switcher.show' title='A list of all 166 Stack Exchange sites'>");
sql.append("            <svg viewBox='0 0 18 19' width='18' height='19' role='icon'><path fill-rule='evenodd' d='M0 14a2 2 0 0 0 2 2h10v3l3-3h1a2 2 0 0 0 2-2v-2H0v2zM16 0H2a2 2 0 0 0-2 2v2h18V2a2 2 0 0 0-2-2zM0 6h18v4H0V6z' /></svg>");
sql.append("        </a>");
sql.append("    </li>");
sql.append("        </ol>");
sql.append("    </nav>");
sql.append("        <div class='-ctas'>");
sql.append("                    <a href='https://stackoverflow.com/users/login?ssrc=head&returnurl=http%3a%2f%2fstackoverflow.com%2fquestions%2f15889331%2fjava-server-socket-sending-html-code-to-browser' class='login-link btn-clear' rel='nofollow'>Log In</a>");
sql.append("                        <a href='https://stackoverflow.com/users/signup?ssrc=head&returnurl=%2fusers%2fstory%2fcurrent&amp;utm_source=stackoverflow.com&amp;utm_medium=dev-story&amp;utm_campaign=signup-redirect' class='login-link btn' rel='nofollow'>Sign Up</a>");
sql.append("        </div>");
sql.append("</div>");
sql.append("    </div>");
sql.append("</header>");
sql.append("    <script>");
sql.append("        StackExchange.ready(function () { StackExchange.topbar.init(); });");
sql.append("            StackExchange.scrollPadding.setPaddingTop(60, 10);     </script>");
sql.append("    <div class='container'>");
sql.append("        <div id='content' class='snippet-hidden'>");
sql.append("<div itemscope itemtype='http://schema.org/Question'>");
sql.append("    <link itemprop='image' href='https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a'>");
sql.append("<div id='herobox' class='alternate'>");
sql.append("    <div class='test'></div>");
sql.append("        <div id='close'>");
sql.append("            <a title='click to minimize'><span>x</span> Dismiss</a>");
sql.append("        </div>");
sql.append("    <div class='content'>");
sql.append("        <b>Fa&#231;a parte da comunidade Stack Overflow</b>");
sql.append("        <div class='separator'></div>");
sql.append("        <div class='blurb'>");
sql.append("            O Stack Overflow &#233; uma comunidade com 6.8 milh&#245;es de programadores como voc&#234;, ajudando uns aos outros.");
sql.append("                <br />");
sql.append("Junte-se a n&#243;s; n&#227;o demora nada:                <br />");
sql.append("        </div>");
sql.append("        <a href='/users/signup?ssrc=hero&amp;returnurl=%2fusers%2fstory%2fcurrent&amp;amp;utm_source=stackoverflow.com&amp;amp;utm_medium=dev-story&amp;amp;utm_campaign=signup-redirect' id='tell-me-more' class='button'>Entrar</a>");
sql.append("    </div>");
sql.append("</div>");
sql.append("<script>");
sql.append("    StackExchange.ready(function () {");
sql.append("        var location = 0;");
sql.append("        if ($('body').hasClass('questions-page')) {");
sql.append("            location = 1;;");
sql.append("        } else if ($('body').hasClass('question-page')) {");
sql.append("            location = 1;;");
sql.append("        } else if ($('body').hasClass('faq-page')) {");
sql.append("            location = 5;;");
sql.append("        } else if ($('body').hasClass('home-page')) {");
sql.append("            location = 3;;");
sql.append("        }");
sql.append("        $('#tell-me-more').click(function () {");
sql.append("            StackExchange.using('gps', function () {");
sql.append("                StackExchange.gps.track('hero.action', { hero_action_type: 'cta', location: location }, true);");
sql.append("            });");
sql.append("        });");
sql.append("        $('#herobox #close').click(function () {");
sql.append("            StackExchange.using('gps', function () {");
sql.append("                StackExchange.gps.track('hero.action', { hero_action_type: 'minimize', location: location }, true);");
sql.append("            });");
sql.append("            $.cookie('hero', 'mini', { path: '/', expires: 365 });");
sql.append("            $.ajax({");
sql.append("                url: '/hero-mini',");
sql.append("                success: function (data) {");
sql.append("                    $('#herobox').fadeOut('fast', function () {");
sql.append("                        $('#herobox').replaceWith(data);");
sql.append("                        $('#herobox-mini').fadeIn('fast');");
sql.append("                    });");
sql.append("                }");
sql.append("            });");
sql.append("            return false;");
sql.append("        });");
sql.append("    });");
sql.append("</script>           <div id='question-header'>");
sql.append("                <h1 itemprop='name'><a href='/questions/15889331/java-server-socket-sending-html-code-to-browser' class='question-hyperlink'>Java Server: Socket sending HTML code to browser</a></h1>            ");
sql.append("<div class='aside-cta'>");
sql.append("    <a href='/questions/ask' class='btn-outlined'>Ask Question</a>");
sql.append("</div>");
sql.append("        </div>");
sql.append("            <div id='mainbar'>");
sql.append("<div class='question' data-questionid='15889331'  id='question'>");
sql.append("    <script>");
sql.append("                var ados = ados || {}; ados.run = ados.run || [];");
sql.append("                ados.run.push(function () { ados_add_placement(22,8277,'adzerk905591647',4).setZone(43); });");
sql.append("            </script>");
sql.append("            <div class='everyonelovesstackoverflow' id='adzerk905591647'></div>    <table>");
sql.append("        <tr>");
sql.append("            <td class='votecell'>");
sql.append("<div class='vote'>");
sql.append("        <input type='hidden' name='_id_' value='15889331'>");
sql.append("        <a class='vote-up-off' title='This question shows research effort; it is useful and clear'>up vote</a>");
sql.append("        <span itemprop='upvoteCount' class='vote-count-post '>0</span>");
sql.append("        <a class='vote-down-off' title='This question does not show any research effort; it is unclear or not useful'>down vote</a>");sql.append("        <a class='star-off' href='#'>favorite</a>");
sql.append("        <div class='favoritecount'><b>2</b></div>");
sql.append("</div>");
sql.append("            </td> ");
sql.append("<td class='postcell'>");
sql.append("<div>");
sql.append("    <div class='post-text' itemprop='text'>");
sql.append("<p>I am trying to write a simple Java program using ServerSockets that will send some HTML code to the browser. Here is my code:</p>");
sql.append("<pre><code>       ServerSocket serverSocket = null;");
sql.append("       try {");
sql.append("             serverSocket = new ServerSocket(55555); ");
sql.append("           } catch (IOException e) ");
sql.append("           {");
sql.append("             System.err.println('Could not listen on port: 55555.');");
sql.append("             System.exit(1);");
sql.append("       }");
sql.append("       Socket clientSocket = null; ");
sql.append("       try {");
sql.append("            clientSocket = serverSocket.accept();");
sql.append("            if(clientSocket != null)                ");
sql.append("                System.out.println('Connected');");
sql.append("       } catch (IOException e) {");
sql.append("             System.err.println('Accept failed.');");
sql.append("             System.exit(1);");
sql.append("      }");
sql.append("     PrintWriter out = new PrintWriter(clientSocket.getOutputStream());");
sql.append("    out.println('HTTP/1.1 200 OK');");
sql.append("    out.println('Content-Type: text/html');");
sql.append("    out.println('\r\n');");
sql.append("    out.println('&lt;p&gt; Hello world &lt;/p&gt;');");
sql.append("    out.flush();");
sql.append("    out.close();");
sql.append("    clientSocket.close();");
sql.append("    serverSocket.close();");
sql.append("</code></pre>");
sql.append("<p>I then go to localhost:55555 in my browser and nothing displays. I know the connection is working because the program outputs 'Connected' as checked in the if statement. I have also tried outputting the data from the inputStream and that works. But the text I am trying to output in the browser is not displaying at all, the program finishes running and I get a 'Problem loading page - the connection has been reset' in my browser, but no text.</p>");
sql.append("<p>I have searched the internet and it seems everyone else coding it this way is having their text display fine, they are having other problems.");
sql.append("How can I fix this? </p>");
sql.append("    </div>");
sql.append("    <div class='post-taglist'>");
sql.append("        <a href='/questions/tagged/java' class='post-tag' title='show questions tagged &#39;java&#39;' rel='tag'>java</a> <a href='/questions/tagged/html' class='post-tag' title='show questions tagged &#39;html&#39;' rel='tag'>html</a> <a href='/questions/tagged/sockets' class='post-tag' title='show questions tagged &#39;sockets&#39;' rel='tag'>sockets</a> <a href='/questions/tagged/browser' class='post-tag' title='show questions tagged &#39;browser&#39;' rel='tag'>browser</a> ");
sql.append("    </div>");
sql.append("    <table class='fw'>");
sql.append("    <tr>");
sql.append("    <td class='vt'>");
sql.append("<div class='post-menu'><a href='/q/15889331' title='short permalink to this question' class='short-link' id='link-post-15889331'>share</a><span class='lsep'>|</span><a href='/posts/15889331/edit' class='suggest-edit-post' title='>improve this question</a></div>        ");
sql.append("    </td>");
sql.append("    <td align='right' class='post-signature'>");
sql.append("<div class='user-info user-hover'>");
sql.append("    <div class='user-action-time'>");
sql.append("        <a href='/posts/15889331/revisions' title='show all edits to this post'>edited <span title='2013-04-09 00:31:16Z' class='relativetime'>Apr 9 '13 at 0:31</span></a>");
sql.append("    </div>");
sql.append("    <div class='user-gravatar32'>");
sql.append("        <a href='/users/207421/ejp'><div class='gravatar-wrapper-32'><img src='https://www.gravatar.com/avatar/5cfe5f7d64f44be04f147295f5c7b88e?s=32&amp;d=identicon&amp;r=PG' alt=' width='32' height='32'></div></a>");
sql.append("    </div>");
sql.append("    <div class='user-details'>");
sql.append("        <a href='/users/207421/ejp'>EJP</a>");
sql.append("        <div class='-flair'>");
sql.append("            <span class='reputation-score' title='reputation score 209,626' dir='ltr'>210k</span><span title='17 gold badges'><span class='badge1'></span><span class='badgecount'>17</span></span><span title='155 silver badges'><span class='badge2'></span><span class='badgecount'>155</span></span><span title='271 bronze badges'><span class='badge3'></span><span class='badgecount'>271</span></span>");
sql.append("        </div>");
sql.append("    </div>");
sql.append("</div>    </td>");
sql.append("    <td class='post-signature owner'>");
sql.append("        <div class='user-info '>");
sql.append("    <div class='user-action-time'>");
sql.append("        asked <span title='2013-04-08 21:28:24Z' class='relativetime'>Apr 8 '13 at 21:28</span>");
sql.append("    </div>");
sql.append("    <div class='user-gravatar32'>");
sql.append("        <a href='/users/2230445/alr'><div class='gravatar-wrapper-32'><img src='https://i.stack.imgur.com/S2FxB.jpg?s=32&amp;g=1' alt=' width='32' height='32'></div></a>");
sql.append("    </div>");
sql.append("    <div class='user-details'>");
sql.append("        <a href='/users/2230445/alr'>ALR</a>");
sql.append("        <div class='-flair'>");
sql.append("            <span class='reputation-score' title='reputation score ' dir='ltr'>76</span><span title='1 gold badge'><span class='badge1'></span><span class='badgecount'>1</span></span><span title='1 silver badge'><span class='badge2'></span><span class='badgecount'>1</span></span><span title='12 bronze badges'><span class='badge3'></span><span class='badgecount'>12</span></span>");
sql.append("        </div>");
sql.append("    </div>");
sql.append("</div>");
sql.append("    </td>");
sql.append("    </tr>");
sql.append("    </table>");
sql.append("</div>");
sql.append("</td>");
sql.append("        </tr>          ");
sql.append("<tr>");
sql.append("    <td class='votecell'></td>");
sql.append("    <td>");
sql.append("        <div id='comments-15889331' class='comments '>");
sql.append("            <table>");
sql.append("                <tbody data-remaining-comments-count='0'");
sql.append("                       data-canpost='false'");
sql.append("                       data-cansee='true'");
sql.append("                       data-comments-unavailable='false'");
sql.append("                       data-addlink-disabled='true'>");
sql.append("    <tr id='comment-22624390' class='comment '>");
sql.append("        <td>");
sql.append("            <table>");
sql.append("                <tbody>");
sql.append("                    <tr>");
sql.append("                        <td class=' comment-score'>");
sql.append("                                &nbsp;&nbsp;");
sql.append("                        </td>");
sql.append("                        <td>");
sql.append("                                &nbsp;");
sql.append("                        </td>");
sql.append("                    </tr>");
sql.append("                </tbody>");
sql.append("            </table>");
sql.append("        </td>");
sql.append("        <td class='comment-text'>");
sql.append("            <div style='display: block;' class='comment-body'>");
sql.append("                <span class='comment-copy'>what browser did you test? this code worked for me in chrome and firefox</span>");
sql.append("                    &ndash;&nbsp;<a href='/users/1999393/fmodos'");
sql.append("                       title='3,846 reputation'");
sql.append("                       class='comment-user'>fmodos</a>");
sql.append("                <span class='comment-date' dir='ltr'><span title='2013-04-08 21:33:39Z' class='relativetime-clean'>Apr 8 '13 at 21:33</span></span>");
sql.append("                                                                            </div>");
sql.append("                    </td>");
sql.append("</tr>    </table>");
sql.append("</div>");
sql.append("<div class='newsletter-anon'>");
sql.append("    <img src='https://cdn.sstatic.net/Sites/stackoverflow/img/apple-touch-icon.png?v=c78bd457575a' class='newsletter-logo' />");
sql.append("    <div class='newsletter-container'>");
sql.append("        <h2>Did you find this question interesting? Try our newsletter</h2>");
sql.append("        <p class='newsletter-description'>");
sql.append("            Sign up for our newsletter and get our top new questions delivered to your inbox (<a href='https://stackexchange.com/newsletters/newsletter?site=stackoverflow.com' id='newsletter-preview'>see an example</a>).");
sql.append("        </p>");
sql.append("        <form id='anon-newsletter-form' data-error='There was a problem signing up for the newsletter. Please try again later.'>");
sql.append("            <input type='email' id='newsletter-email-input' placeholder='email address' title='your email address' />");
sql.append("            <input type='submit' value='Subscribe' id='newsletter-email-submit'/>");
sql.append("        </form>");
sql.append("        <div style='margin-top: 10px; float:right;' class='dno cbt newsletter-status-confirmed'>");
sql.append("            <b>Subscribed!</b>");
sql.append("        </div>");
sql.append("        <div style='margin-top: 10px; float:right;' class='dno cbt newsletter-status-unconfirmed'>");
sql.append("            <b>Success!</b> Please click the link in the confirmation email to activate your subscription.");
sql.append("        </div>");
sql.append("    </div>");
sql.append("</div>");
sql.append("<script>");
sql.append("    StackExchange.ready(function () {");
sql.append("        StackExchange.newsletterAd.init();");
sql.append("    });");
sql.append("    $('#anon-newsletter-form').submit(function () {");
sql.append("        var $form = $(this);");
sql.append("        var $input = $form.find('#newsletter-email-input');");
sql.append("        var $submit = $form.find('#newsletter-email-submit');");
sql.append("        var $container = $form.closest('.newsletter-container');");
sql.append("        var email = $.trim($input.val());");
sql.append("        if (email.length == 0) {");
sql.append("            return false;");
sql.append("        }");
sql.append("        StackExchange.helpers.addSpinner($form);");
sql.append("        $.ajax({");
sql.append("            url: '/newsletter/signup/anon',");
sql.append("            type: 'POST',");
sql.append("            dataType: 'json',");
sql.append("            data: { fkey: StackExchange.options.user.fkey, email: email, viaAnonNewsletterAd: true },");
sql.append("            success: function (data) {");
sql.append("                if (!data.error && (data.status == 'confirmed' || data.status == 'unconfirmed')) {");
sql.append("                    $input.attr('disabled', true);");
sql.append("                    $submit.remove();");
sql.append("                    $container.find('.newsletter-status-' + data.status).show();");
sql.append("                }");
sql.append("                else {");
sql.append("                    $container.showErrorMessage(data.error || $form.data('error'));");
sql.append("                }");
sql.append("            },");
sql.append("            error: function () {");
sql.append("                $container.showErrorMessage($form.data('error'));");
sql.append("            },");
sql.append("            complete: function () {");
sql.append("                StackExchange.helpers.removeSpinner($form);");
sql.append("            }");
sql.append("        });");
sql.append("        return false;");
sql.append("    });");
sql.append("</script> ");
sql.append("<a name='15891356'></a>");
sql.append("<div id='answer-15891356' class='answer' data-answerid='15891356'  itemscope itemtype='http://schema.org/Answer'>");
sql.append("    <table>");
sql.append("        <tr>");
sql.append("            <td class='votecell'>");
sql.append("<div class='vote'>");
sql.append("        <input type='hidden' name='_id_' value='15891356'>");
sql.append("        <a class='vote-up-off' title='This answer is useful'>up vote</a>");
sql.append("        <span itemprop='upvoteCount' class='vote-count-post '>0</span>");
sql.append("        <a class='vote-down-off' title='This answer is not useful'>down vote</a>");
sql.append("</div>");
sql.append("            </td>");
sql.append("<td class='answercell'>");
sql.append("    <div class='post-text' itemprop='text'>");
sql.append("<ol>");
sql.append("<li><p>The line terminator in HTTP is <code>\r\n.</code> This means that you shouldn't use <code>println()</code>, you should use <code>print()</code> and add an explicit <code>\r\n</code> yourself to each line.</p></li>");
sql.append("<li><p>The result of an HTTP GET is supposed to be an HTML document, not a fragment. Browsers are entitled to ignore or complain. Send this:</p>");
sql.append("<p>&lt;html>");
sql.append("&lt;head/>");
sql.append("&lt;body>");
sql.append("&lt;p> Hello world &lt;/p>");
sql.append("&lt;/body>");
sql.append("&lt;/html></p></li>");
sql.append("</ol>");
sql.append("    </div>");
sql.append("    <table class='fw'>");
sql.append("    <tr>");
sql.append("    <td class='vt'>");
sql.append("<div class='post-menu'><a href='/a/15891356' title='short permalink to this answer' class='short-link' id='link-post-15891356'>share</a><span class='lsep'>|</span><a href='/posts/15891356/edit' class='suggest-edit-post' title=''>improve this answer</a></div>                    </td>");
sql.append("    <td align='right' class='post-signature'>   ");
sql.append("    <div class='user-info user-hover'>");
sql.append("    <div class='user-action-time'>");
sql.append("        answered <span title='2013-04-09 00:32:17Z' class='relativetime'>Apr 9 '13 at 0:32</span>");
sql.append("    </div>");
sql.append("    <div class='user-gravatar32'>");
sql.append("        <a href='/users/207421/ejp'><div class='gravatar-wrapper-32'><img src='https://www.gravatar.com/avatar/5cfe5f7d64f44be04f147295f5c7b88e?s=32&amp;d=identicon&amp;r=PG' alt=' width='32' height='32'></div></a>");
sql.append("    </div>");
sql.append("    <div class='user-details'>");
sql.append("        <a href='/users/207421/ejp'>EJP</a>");
sql.append("        <div class='-flair'>");
sql.append("            <span class='reputation-score' title='reputation score 209,626' dir='ltr'>210k</span><span title='17 gold badges'><span class='badge1'></span><span class='badgecount'>17</span></span><span title='155 silver badges'><span class='badge2'></span><span class='badgecount'>155</span></span><span title='271 bronze badges'><span class='badge3'></span><span class='badgecount'>271</span></span>");
sql.append("        </div>");
sql.append("    </div>");
sql.append("</div>");
sql.append("    </td>");
sql.append("    </tr>");
sql.append("    </table>");
sql.append("</td>");
sql.append("        </tr>");
sql.append("<tr>");
sql.append("    <td class='votecell'></td>");
sql.append("    <td>");
sql.append("        <div id='comments-15891356' class='comments  dno'>");
sql.append("            <table>");
sql.append("                <tbody data-remaining-comments-count='0'");
sql.append("                       data-canpost='false'");
sql.append("                       data-cansee='true'");
sql.append("                       data-comments-unavailable='false'");
sql.append("                       data-addlink-disabled='true'>");
sql.append("                        <tr><td></td><td></td></tr>");
sql.append("                </tbody>");
sql.append("            </table>");
sql.append("        </div>");
sql.append("        <div id='comments-link-15891356' data-rep=50 data-anon=true>");
sql.append("                <a class='js-add-link comments-link disabled-link '");
sql.append("                   title='Use comments to ask for more information or suggest improvements. Avoid comments like “+1” or “thanks”.'");
sql.append("                   >add a comment</a><span class='js-link-separator dno'>&nbsp;|&nbsp;</span>");
sql.append("            <a class='js-show-link comments-link dno' title='expand to show all comments on this post' href=# onclick=''></a>");
sql.append("        </div>         ");
sql.append("    </td>");
sql.append("</tr>    </table>");
sql.append("</div>");
sql.append("<a name='39521741'></a>");
sql.append("<div id='answer-39521741' class='answer' data-answerid='39521741'  itemscope itemtype='http://schema.org/Answer'>");
sql.append("    <table>");
sql.append("        <tr>");
sql.append("            <td class='votecell'>");
sql.append("<div class='vote'>");
sql.append("        <input type='hidden' name='_id_' value='39521741'>");
sql.append("        <a class='vote-up-off' title='This answer is useful'>up vote</a>");
sql.append("        <span itemprop='upvoteCount' class='vote-count-post '>0</span>");
sql.append("        <a class='vote-down-off' title='This answer is not useful'>down vote</a>");
sql.append("</div>");
sql.append("            </td>           ");
sql.append("<td class='answercell'>");
sql.append("    <div class='post-text' itemprop='text'>");
sql.append("<p>You need to need to set the PrintWriter to autoflush when it prints.</p>");
sql.append("<p><code>PrintWriter out = new PrintWriter(clientSocket.getOutputStream());</code></p>");
sql.append("<p>should be</p>");
sql.append("<p><code>PrintWriter out = new PrintWriter(clientSocket.getOutputStream(), true);</code></p>");
sql.append("    </div>");
sql.append("    <table class='fw'>");
sql.append("    <tr>");
sql.append("    <td class='vt'>");
sql.append("<div class='post-menu'><a href='/a/39521741' title='short permalink to this answer' class='short-link' id='link-post-39521741'>share</a><span class='lsep'>|</span><a href='/posts/39521741/edit' class='suggest-edit-post' title=''>improve this answer</a></div>                    </td>");
sql.append("    <td align='right' class='post-signature'>   ");
sql.append("    <div class='user-info '>");
sql.append("    <div class='user-action-time'>");
sql.append("        answered <span title='2016-09-15 23:23:31Z' class='relativetime'>Sep 15 '16 at 23:23</span>");
sql.append("    </div>");
sql.append("    <div class='user-gravatar32'>");
sql.append("        <a href='/users/3850325/h3dg3wytch'><div class='gravatar-wrapper-32'><img src='https://i.stack.imgur.com/EqxUc.jpg?s=32&amp;g=1' alt=' width='32' height='32'></div></a>");
sql.append("    </div>");
sql.append("    <div class='user-details'>");
sql.append("        <a href='/users/3850325/h3dg3wytch'>h3dg3Wytch</a>");
sql.append("        <div class='-flair'>");
sql.append("            <span class='reputation-score' title='reputation score ' dir='ltr'>1</span><span title='2 bronze badges'><span class='badge3'></span><span class='badgecount'>2</span></span>");
sql.append("        </div>");
sql.append("    </div>");
sql.append("</div>");
sql.append("    </td>");
sql.append("    </tr>");
sql.append("    </table>");
sql.append("</td>");
sql.append("        </tr>  ");
sql.append("<tr>");
sql.append("    <td class='votecell'></td>");
sql.append("    <td>");
sql.append("        <div id='comments-39521741' class='comments  dno'>");
sql.append("            <table>");
sql.append("                <tbody data-remaining-comments-count='0'");
sql.append("                       data-canpost='false'");
sql.append("                       data-cansee='true'");
sql.append("                       data-comments-unavailable='false'");
sql.append("                       data-addlink-disabled='true'>");
sql.append("                        <tr><td></td><td></td></tr>");
sql.append("                </tbody>");
sql.append("            </table>");
sql.append("        </div>");
sql.append("        <div id='comments-link-39521741' data-rep=50 data-anon=true>");
sql.append("                <a class='js-add-link comments-link disabled-link '");
sql.append("                   title='Use comments to ask for more information or suggest improvements. Avoid comments like “+1” or “thanks”.'");
sql.append("                   >add a comment</a><span class='js-link-separator dno'>&nbsp;|&nbsp;</span>");
sql.append("            <a class='js-show-link comments-link dno' title='expand to show all comments on this post' href=# onclick=''></a>");
sql.append("        </div>         ");
sql.append("    </td>");
sql.append("</tr>    </table>");
sql.append("<script>var p = 'http', d = 'static'; if (document.location.protocol == 'https:') { p += 's'; d = 'engine'; } var z = document.createElement('script'); z.type = 'text/javascript'; z.async = true; z.src = p + '://' + d + '.adzerk.net/ados.js'; var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(z, s);</script>");
sql.append("<script>");
sql.append("    var ados = ados || {};");
sql.append("    ados.run = ados.run || [];");
sql.append("        ados.run.push(function () {");
sql.append("                setTimeout(function () { $('#adzerk-user-match').remove(); }, window.AUMIframeDone ? 0 : 2000);");
sql.append("                ados_setKeywords('java,html,sockets,browser');; ados_load();");
sql.append("        });         ");
sql.append("</script>");
sql.append("    <script>");
sql.append("            (function(i, s, o, g, r, a, m) {");
sql.append("                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function() { (i[r].q = i[r].q || []).push(arguments) }, i[r].l = 1 * new Date(); a = s.createElement(o),");
sql.append("                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m);");
sql.append("            })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');");
sql.append("                ga('create', 'UA-5620270-1');");
sql.append("                ga('create', 'UA-5620270-59', {name: 'pageData', sampleRate: 5 });");
sql.append("                ga('set', 'dimension2', '|java|html|sockets|browser|');");
sql.append("                ga('pageData.set', 'dimension2', '|java|html|sockets|browser|');");
sql.append("                ga('send', 'pageview');");
sql.append("                ga('pageData.send', 'pageview');");
sql.append("        var _qevents = _qevents || [],");
sql.append("            _comscore = _comscore || [];");
sql.append("        (function () {");
sql.append("            var ssl='https:'==document.location.protocol,");
sql.append("                s=document.getElementsByTagName('script')[0],");
sql.append("                qc=document.createElement('script');");
sql.append("                qc.async = true;");
sql.append("                qc.src = (ssl ? 'https://secure' : 'http://edge') + '.quantserve.com/quant.js';");
sql.append("                s.parentNode.insertBefore(qc, s);");
sql.append("                _qevents.push({ qacct: 'p-c1rF4kxgLUzNc' });");
sql.append("                            var sc=document.createElement('script');");
sql.append("                sc.async=true;");
sql.append("                sc.src=(ssl?'https://sb':'http://b') + '.scorecardresearch.com/beacon.js';");
sql.append("                s.parentNode.insertBefore(sc, s);");
sql.append("                _comscore.push({ c1: '2', c2: '17440561' });");
sql.append("        })();");
sql.append("    </script>");
sql.append("            <script type='text/javascript'>");
sql.append("                (function(appendChild) {");
sql.append("                    Node.prototype.appendChild = function() {");
sql.append("                        var parent = this;");
sql.append("                        var newNode = arguments[0];");
sql.append("                        if (parent.nodeName === 'HEAD'");
sql.append("                            && newNode");
sql.append("                            && newNode.nodeName === 'SCRIPT'");
sql.append("                            && newNode.src) {");
sql.append("                            window.setTimeout(function() {");
sql.append("                                var service = result[1];");
sql.append("                                if (service) {");
sql.append("                                    if (service === 'Autocompletion') service =  2;");
sql.append("                                    else if (service === 'Place') service = 1;");
sql.append("                                    else service = 0;");
sql.append("                                    StackExchange.using('gps', function() {");
sql.append("                                        StackExchange.gps.track('google_maps_places_api.call', { service: service });");
sql.append("                                    });");
sql.append("                                }");
sql.append("                            }, 0);");
sql.append("                        }");
sql.append("                        return appendChild.apply(this, arguments);");
sql.append("                    };");
sql.append("                })(Node.prototype.appendChild);");
sql.append("            </script>");
sql.append("    </body>");
sql.append("</html>");
		
		while(true){
			try {
		          serverSocket = new ServerSocket(8080); 
		        } catch (IOException e) 
		        {
		          System.err.println("Could not listen on port: 55555.");
		          System.exit(1);
		    }

		    Socket clientSocket = null; 
		    try {
		         clientSocket = serverSocket.accept();

		         if(clientSocket != null)                
		             System.out.println("Connected");

		    } catch (IOException ex) {
		          System.err.println("Accept failed.");
		          System.exit(1);
		   }

		  PrintWriter out = new PrintWriter(clientSocket.getOutputStream());


//		 out.println("HTTP/1.1 200 OK");
//		 out.println("Content-Type: text/html");
//		 out.println("\r\n");
//		 out.println("<p> Hello world </p>");
		 out.print(sql);
		 out.flush();

		 out.close();

		 clientSocket.close();
		 serverSocket.close();
		}
		
	    
	}
}
